---
title: 'Whats next?'
teaching: 10
exercises: 2
link-external-newwindow: true
---

:::::::::::::::::::::::::::::::::::::: questions 

- "What is the next step?"

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- "Get an idea about what to do to learn more"

::::::::::::::::::::::::::::::::::::::::::::::::


The goal of this course was to give an introduction on how to work
with API in general.

For many of the major services online, there exists specialized packages
making it easier to work with their API. 

Ideally we would have a complete list here.

Less ambitiously we would have a solid selection.

For now we have three.

The [gargle package](https://cran.r-project.org/web/packages/gargle/index.html),
provides tools for working with the Google APIs.


[The Guardian](https://open-platform.theguardian.com/) have an open API providing
access to >2 million articles from that newspaper. You will need to register for
an API key, but it is free.

[Wikidata](https://www.wikidata.org/wiki/Wikidata:REST_API) handles factual data
for the Wikipedia infrastructure. 


You can find other courses, covering other aspects of R in our course calendars:

- [Roskilde University Library](https://roskildeuni.libcal.com/){target="_blank"}
- [Copenhagen University Library](https://kubkalender.kb.dk/calendar/datalab?cid=6416&t=d&d=0000-00-00&cal=6416&inc=0){target="_blank"}



::::::::::::::::::::::::::::::::::::: keypoints 

- "Practice makes perfect"
- "KUB Datalab offers lots of courses and consultations"
- "The web is overflowing with tutorials and courses"

::::::::::::::::::::::::::::::::::::::::::::::::

